-- 코드를 작성해주세요
WITH GENERATION AS (
    SELECT
        T1.ID AS SECOND_ID, 
        T1.PARENT_ID AS SECOND_PARENT_ID,
        T2.ID AS FIRST_ID,
        T2.PARENT_ID AS FIRST_PARENT_ID
    FROM
        ECOLI_DATA AS T1
        JOIN ECOLI_DATA AS T2
        ON T1.PARENT_ID = T2.ID
)
SELECT
    ECOLI_DATA.ID AS ID
FROM
    ECOLI_DATA
    JOIN GENERATION
    ON ECOLI_DATA.PARENT_ID = GENERATION.SECOND_ID
WHERE
    FIRST_PARENT_ID IS NULL
ORDER BY
    1 ASC
;