-- 코드를 작성해주세요
SELECT
    ITEM_INFO.ITEM_ID,
    ITEM_INFO.ITEM_NAME,
    ITEM_INFO.RARITY
FROM
    ITEM_INFO
    LEFT JOIN ITEM_TREE
    ON ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
WHERE
    ITEM_TREE.PARENT_ITEM_ID IS NULL
ORDER BY
    1 DESC;