-- 코드를 작성해주세요
WITH RANKED AS (
    SELECT
        ID,
        PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 AS PERCENT
    FROM
       ECOLI_DATA
)

SELECT
    ID,
    CASE
        WHEN PERCENT <= 25 THEN 'CRITICAL'
        WHEN PERCENT <= 50 THEN 'HIGH'
        WHEN PERCENT <= 75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM
    RANKED
ORDER BY
    1 ASC
;