-- 코드를 입력하세요
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, SCORE
FROM REST_INFO 
    JOIN ( SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
        FROM REST_REVIEW
        GROUP BY REST_ID ) AS RW_TABLE
    ON REST_INFO.REST_ID = RW_TABLE.REST_ID
WHERE ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC
    

-- 레스토랑별 평균 리뷰
# SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS RW
# FROM REST_REVIEW
# GROUP BY REST_ID