-- 코드를 작성해주세요
WITH RECURSIVE ANCESTOR AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM
        ECOLI_DATA
    WHERE
        PARENT_ID IS NULL
UNION
    SELECT
        ECO.ID,
        ECO.PARENT_ID,
        (ANC.GENERATION + 1) AS GENERATION
    FROM   
        ECOLI_DATA AS ECO,
        ANCESTOR AS ANC
    WHERE
        ECO.PARENT_ID = ANC.ID
)

SELECT
    COUNT(*) AS 'COUNT',
    GENERATION
FROM
    ANCESTOR
WHERE
    ID NOT IN (SELECT PARENT_ID FROM ANCESTOR WHERE PARENT_ID IS NOT NULL)
GROUP BY
    2
ORDER BY
    2
;
    