-- 코드를 입력하세요
SELECT
    APNT_NO
    , PT_NAME
    , PT_NO
    , APPOINTMENT.MCDP_CD AS MCDP_CD
    , DR_NAME
    , APNT_YMD
FROM
    APPOINTMENT
JOIN PATIENT
    USING(PT_NO)
JOIN DOCTOR 
    ON DOCTOR.DR_ID = APPOINTMENT.MDDR_ID AND DOCTOR.MCDP_CD = APPOINTMENT.MCDP_CD
WHERE
    APPOINTMENT.MCDP_CD = 'CS'
    AND APNT_YMD LIKE '2022-04-13%'
    AND APNT_CNCL_YN = 'N'
ORDER BY
    APNT_YMD ASC;