-- 코드를 입력하세요
SELECT
    USED_GOODS_USER.USER_ID
    , USED_GOODS_USER.NICKNAME
    , SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD
    JOIN USED_GOODS_USER
    ON USED_GOODS_USER.USER_ID = USED_GOODS_BOARD.WRITER_ID
WHERE
    USED_GOODS_BOARD.STATUS = 'DONE'
GROUP BY
    1, 2
HAVING
    SUM(PRICE) >= 700000
ORDER BY
    3 ASC;