-- 코드를 작성해주세요
SELECT 
    PARENT.ITEM_ID, 
    PARENT.ITEM_NAME, 
    PARENT.RARITY
FROM 
    ITEM_INFO
JOIN 
    (SELECT 
        ITEM_TREE.ITEM_ID, 
        ITEM_TREE.PARENT_ITEM_ID, 
        ITEM_INFO.ITEM_NAME, 
        ITEM_INFO.RARITY
    FROM ITEM_TREE
    LEFT JOIN ITEM_INFO 
        ON ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID) AS PARENT
    ON ITEM_INFO.ITEM_ID = PARENT.PARENT_ITEM_ID
WHERE 
    ITEM_INFO.RARITY = 'RARE'
ORDER BY 
    PARENT.ITEM_ID DESC



