-- 코드를 작성해주세요
SELECT 
    CHILD.ID AS ID, 
    CHILD.GENOTYPE AS GENOTYPE, 
    PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM 
    ECOLI_DATA AS CHILD
    JOIN ECOLI_DATA AS PARENT
    ON CHILD.PARENT_ID = PARENT.ID
WHERE 
    CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY 
    ID ASC