-- 코드를 작성해주세요
WITH MAXSIZE AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS MAXSIZE_YEAR,
        MAX(SIZE_OF_COLONY) AS 'MAX_SIZE'
    FROM
        ECOLI_DATA
    GROUP BY
        1
)
SELECT
    YEAR(DIFFERENTIATION_DATE) AS 'YEAR',
    MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM
    ECOLI_DATA
    JOIN MAXSIZE
    ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MAXSIZE.MAXSIZE_YEAR
ORDER BY
    1 ASC,
    2 ASC