-- 코드를 작성해주세요
SELECT
    SUM(SCORE) AS SCORE,
    EMP_NO,
    EMP_NAME,
    POSITION,
    EMAIL
FROM
    HR_EMPLOYEES
    LEFT JOIN HR_GRADE
    USING(EMP_NO)
    # ON HR_EMPLOYEES.EMP_NO = HR_GRADE.EMP_NO
    LEFT JOIN HR_DEPARTMENT
    USING(DEPT_ID)
    # ON HR_EMPLOYEES.DEPT_ID = HR_DEPARTMENT.DEPT_ID
GROUP BY
    2
ORDER BY
    1 DESC
LIMIT 1