-- 코드를 작성해주세요
WITH FRONTEND_CTE AS (
    SELECT NAME, CODE
    FROM SKILLCODES 
    WHERE CATEGORY = 'Front End'
)
SELECT
    CASE
        WHEN EXISTS (SELECT 1  FROM FRONTEND_CTE AS FC WHERE D.SKILL_CODE & FC.CODE = FC.CODE)
            AND D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') != 0
            THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') != 0
            THEN 'B'
        WHEN EXISTS (SELECT 1 FROM FRONTEND_CTE AS FC WHERE D.SKILL_CODE & FC.CODE = FC.CODE)
            THEN 'C'
    END AS GRADE
    , ID
    , EMAIL
FROM
    DEVELOPERS AS D
WHERE
    D.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') != 0
    OR EXISTS (SELECT 1 FROM FRONTEND_CTE AS FC WHERE D.SKILL_CODE & FC.CODE = FC.CODE)
ORDER BY
    1 ASC,
    2 ASC;